# Generated by Django 3.1.7 on 2021-02-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekordy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text="It is text describing user's problem here")),
                ('waga', models.IntegerField(help_text='It is numeric representation of waga')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
