# Generated by Django 3.1.7 on 2021-02-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210228_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rekordy',
            new_name='Rekord',
        ),
    ]
