# Generated by Django 3.1.7 on 2021-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20210228_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kod_odpadu',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
