# Generated by Django 3.1.7 on 2021-02-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20210228_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kod_odpadu',
            new_name='KodOdpadu',
        ),
    ]
